### ISSUE TITLE
Question about explanation itemsets 

### ISSUE THREAD

**Issue by LuisaWerner** [amrmalkhatib/CEGA#1]
Hi, 

My name is Luisa and I noticed your work on “Explaining Predictions by Characteristic Rules” on the ECML Conference last week. I read the paper in more details and I am really interested in your work. 

May I ask you a questions about it? 

One thing that was not clear to me is how you mine the explanations and how you create the explanation itemsets. I got a bit lost at that point. Do you have a toy example to explain me how you obtain the rules and how they would look like? 

Thanks a lot! 
Luisa

**Comment by amrmalkhatib** [comment]
Hi Luisa,

Simply we convert the explanations into itemsets of conditions (or statements) then we apply an association rule mining algorithm to the itemsets.

We have two cases of explanations that are treated differently:
  
  1- explanatory rules:
      All the conditions and the consequent class in the explanatory rule are added to one item set.
  
  2- Feature importance scores:
      We consider the features that supported the predicted class label.
      Then we convert them to conditions as follows:
      a- Binary features can be added to the itemset as conditions, e.g., green == 1
      b- Categorical features are added as conditions, e.g., gender == male
      c- Continuous features are binned into intervals, e.g., 1000 < income ≤ 5000
   
    These conditions are added to one itemset with the predicted class label as well.


I hope this answer is helpful.
